### ISSUE TITLE
Deployment checklist 

### ISSUE THREAD

**Issue by xcollantes** [xcollantes/portfolio#18]
Before showing to the internet the site: 

- [ ] Password protect?  Decide if you want to turn on the `key=` argument 
- [ ] `.env.production` is as you intend?  
- [ ] Remove `console.log()` and `console.debug()` unless wherever intended.  
- [ ] Check each `TODO` and action unless intended.  
- [ ] Check for TypeScript errors
