### ISSUE TITLE
[Tracker] Add blogs

### ISSUE THREAD

**Issue by xcollantes** [xcollantes/portfolio#59]
Ongoing tracking for adding blog and work experience articles.  

# TODO

## Work experience 

- [x] Dean of business video 
- [x] Google TSC work 
- [ ] Streamlit stock analysis 
- [x] RPI camera 
- [x] Rx Blockchain 
- [ ] GCP certificate 
- [ ] Amazon price graph 
- [ ] Checkmate
- [x] Portfolio
- [x] Gonzaga housing
- [x] Business intell engineer internship 

## Blogs 

- [x] Python notes
- [ ] Cloud blog
- [ ] Firebase common pitfalls 
- [x] Ham radio stuff (Blog)

**Comment by xcollantes** [comment]
# TODO

- [ ] Dean of business video 
- [ ] Amazon price graph 
- [ ] Business intell engineer internship
